Update buildspec.yml

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -12,9 +12,14 @@ phases:
       - echo "Publishing new version..."
       - NEW_VERSION=$(aws lambda publish-version --function-name mylambdafunction-1 --query Version --output text)
       - echo "New Version: $NEW_VERSION"
-      - if [ -z "$NEW_VERSION" ] || [ "$NEW_VERSION" = "0" ]; then echo "Error publishing new version!"; exit 1; fi
+      - |
+        if [ -z "$NEW_VERSION" ] || [ "$NEW_VERSION" = "0" ]; then 
+          echo "Error publishing new version!"
+          exit 1
+        fi
       - echo "Updating alias to new version..."
       - aws lambda update-alias --function-name mylambdafunction-1 --name Prod --function-version "$NEW_VERSION"
 
 artifacts:
-  files: deployment.zip
+  files:
+    - deployment.zip
